# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: SetUp NodeJS
        run: actions/setup-node@v2-beta
        with:
          node-version:12
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.3.0
      - name: Install Surge
        uses: npm install -g surge
      - name: Create Build Folder
        uses: yarn build
      - name: Deploy to Surge
        uses: surge ./build https://mubashar-covid-19-tracker-app.surge.sh/ --token --token ${{secrets.SURGE_TOKEN}}
